# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35d11de581144b0beb55877aa334a9ca181a77fee56913f3a2697083384d776baf04ef4043cbf42716ddafb5985b58546e32b30948e6e44fbc64b8f22a60ddd1

test:
  secret_key_base: 318a173615b6289eb3a606760d72f9eeb752f397d4b46a4856d0137d885eb13cc3fe87b618bfd4beeaea98eb65c88b5bd4bd509f8550d9868e0c8aad42d4dca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
